import {
  Calendar,
  CheckSquare,
  ClipboardList,
  Contact2,
  File,
  FileText,
  FilePlus2,
  FileSearch2,
  FolderKanban,
  ScrollText,
  User,
  Users,
  BarChart3,
  Settings,
  LayoutDashboard,
  Contact2,
  Scale,
  FileSearch2,
  FilePlus2,
  FolderKanban,
  BadgeCheck,
  AlertTriangle,
  AlertCircle,
  Clock4,
  AlertOctagon
} from "lucide-react"

import {
  Patient,
  PatientFormData,
  Employee,
  EmployeeFormData
} from "./types"

export const navItems = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/dashboard",
  },
  {
    label: "Patients",
    icon: Users,
    href: "/patients",
  },
  {
    label: "Calendar",
    icon: Calendar,
    href: "/calendar",
  },
  {
    label: "Documents",
    icon: FileText,
    href: "/documents",
  },
  {
    label: "Tasks",
    icon: CheckSquare,
    href: "/tasks",
  },
  {
    label: "Contacts",
    icon: Contact2,
    href: "/contacts",
  },
  {
    label: "Settings",
    icon: Settings,
    href: "/settings",
  },
]

export const doctorNavItems = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/dashboard",
  },
  {
    label: "Patients",
    icon: Users,
    href: "/patients",
  },
  {
    label: "Calendar",
    icon: Calendar,
    href: "/calendar",
  },
  {
    label: "Documents",
    icon: FileText,
    href: "/documents",
  },
  {
    label: "Tasks",
    icon: CheckSquare,
    href: "/tasks",
  },
  {
    label: "Contacts",
    icon: Contact2,
    href: "/contacts",
  },
]

export const patientNavItems = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/dashboard",
  },
  {
    label: "Doctors",
    icon: Users,
    href: "/doctors",
  },
  {
    label: "Calendar",
    icon: Calendar,
    href: "/calendar",
  },
  {
    label: "Documents",
    icon: FileText,
    href: "/documents",
  },
  {
    label: "Contacts",
    icon: Contact2,
    href: "/contacts",
  },
]

export const mockPatients: Patient[] = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
    dateOfBirth: "1990-01-01",
    gender: "Male",
    insuranceProvider: "Blue Cross",
    insuranceId: "123456789",
    primaryCarePhysician: "Dr. Smith",
    medicalHistory: "None",
    allergies: "None",
    medications: "None",
    createdAt: "2021-01-01T00:00:00.000Z",
    updatedAt: "2021-01-01T00:00:00.000Z",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Doe",
    email: "jane.doe@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
    dateOfBirth: "1990-01-01",
    gender: "Female",
    insuranceProvider: "Blue Cross",
    insuranceId: "123456789",
    primaryCarePhysician: "Dr. Smith",
    medicalHistory: "None",
    allergies: "None",
    medications: "None",
    createdAt: "2021-01-01T00:00:00.000Z",
    updatedAt: "2021-01-01T00:00:00.000Z",
  },
  {
    id: "3",
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
    dateOfBirth: "1990-01-01",
    gender: "Male",
    insuranceProvider: "Blue Cross",
    insuranceId: "123456789",
    primaryCarePhysician: "Dr. Smith",
    medicalHistory: "None",
    allergies: "None",
    medications: "None",
    createdAt: "2021-01-01T00:00:00.000Z",
    updatedAt: "2021-01-01T00:00:00.000Z",
  },
  {
    id: "4",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "123-456-7890",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zip: "12345",
    dateOfBirth: "1990-01-01",
    gender: "Female",
    insuranceProvider: "Blue Cross",
    insuranceId: "123456789",
    primaryCarePhysician: "Dr. Smith",
    medicalHistory: "None",
    allergies: "None",
    medications: "None",
    createdAt: "2021-01-01T00:00:00.000Z",
    updatedAt: "2021-01-01T00:00:00.000Z",
  },
]

export const mockPatientFormData: PatientFormData = {
  firstName: "John",
  lastName: "Doe",
  email: "john.doe@example.com",
  phone: "123-456-7890",
  address: "123 Main St",
  city: "Anytown",
  state: "CA",
  zip: "12345",
  dateOfBirth: "1990-01-01",
  gender: "Male",
  insuranceProvider: "Blue Cross",
  insuranceId: "123456789",
  primaryCarePhysician: "Dr. Smith",
  medicalHistory: "None",
  allergies: "None",
  medications: "None",
}

export const mockEmployees: Employee[] = [
  {
    id: '1',
    emp_id: 'EMP-001',
    full_name: 'John Smith',
    email: 'john.smith@company.com',
    ph_no: '+1234567890',
    role: 'admin',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    emp_id: 'EMP-002',
    full_name: 'Jane Doe',
    email: 'jane.doe@company.com',
    ph_no: '+1234567891',
    role: 'drafter',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    emp_id: 'EMP-003',
    full_name: 'Bob Johnson',
    email: 'bob.johnson@company.com',
    ph_no: '+1234567892',
    role: 'filer',
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  }
];
